### ISSUE TITLE
transition property on utils/Frame breaks navigation scroll preservation

### ISSUE THREAD

**Issue by Coronon** [themesberg/flowbite-svelte#950]
### Describe the bug

When navigating _from_ a page that uses the `Navbar` component, scroll preservation of a previously visited site is broken, and the scroll is "all over the place" (depending on browser and kind of navigation [e.g. to anchor tag]). After some digging, I found that the culprit is this line in `**utils/Frame.svelte**:

```svelte
<svelte:element
  this={tag}
  use:use={options}
  bind:this={node}
  transition:transition={params} // <---- This breaks navigation!
  {...$$restProps}
  class={divClass}
  on:click
  on:mouseenter
  on:mouseleave
  on:focusin
  on:focusout
  {role}>
  <slot />
</svelte:element>
```

When pasting the compiled HTML back into svelte instead of the `Navbar` component, or recreating it with a copy and paste of **Frame.svelte** with the transition omitted, everything works again.

This is mainly visible when using the browser back button or `window.history.back()`, but also causes weird behavior when navigation to an anchor tag on Safari, where it just scrolls past the tag ^^

Thank you again for this awesome library! :)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-wvhzf6

Please scroll down until you find the test buttons and wait for hydration on first load :)

### Flowbite version and System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 6.26 GB / 15.95 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: 115.0.5790.102
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.82)
  npmPackages:
    @sveltejs/kit: ^1.20.4 => 1.22.3
    flowbite-svelte: ^0.40.1 => 0.40.1
    svelte: ^4.0.0 => 4.1.0
    vite: ^4.3.0 => 4.3.9
```

**Comment by Coronon** [comment]
This seems to only happen if the `Navbar` component is _inside_ the exchanged component, not if it lives above (e.g. in the layout).

**Comment by Coronon** [comment]
Just for people to track this issue: https://discord.com/channels/457912077277855764/750401468569354431/1147275274631782551

The thread also includes proposed changes that would add a `|nonav` modifier that fixes this issue :)

**Comment by Coronon** [comment]
##### Oh wow... It's just on the Svelte Discord server... I'll just dump the important part here and will update this thread if anything important happens :)
<br/><br/>
I am currently experiencing a bug where a transition on a page will break scroll restoration on navigation between routes.

This caused me to add a `|nonav` modifier to transitions that will prevent them from running when Kit navigates.
I implemented this in Svelte and SvelteKit by using `globalThis` in both the SvelteKit client and Svelte client transition code to communicate that a navigation is happening. The Svelte compiler then adds a little check (just like with `|local`) to prevent the animation from running if Kit is currently navigating.

Now the real question: Is there any preferred/recommended way to communicate between SvelteKit and Svelte? I don't see how I can rely on `beforeNavigate` etc. to fix this issue or not modify the compiler itself. The bug is triggered with even an empty `null_transition` as it's a "race condition" between `requestAnimtionFrame` and the kit navigation code.

This is actually not a bug per the documentation but breaks a lot of UI and could be simply avoided in a non-breaking way for old sites. I'd like some feedback on this "communication" approach so that I can submit my adjustments as a PR.

Issue reproduction:
https://stackblitz.com/edit/sveltejs-kit-template-default-atnnds

Changes in Kit:
https://github.com/Coronon/kit/commit/fa00aea7a97a9918fcb1857aa1376c70698893f4

Changes in Svelte:
https://github.com/Coronon/svelte/commit/8db526159c81c1a4db58bdb4a64a3244117f5304

Related issue: https://github.com/sveltejs/svelte/issues/9028

**Comment by Coronon** [comment]
Added PR that could fix this with a new `condition` property on `TransitionConfig`: https://github.com/sveltejs/svelte/pull/9272

**Comment by rolodato** [comment]
This issue should be opened again. It still exists and have run into it because of using the `Navbar` component repeatedly across different pages. I was able to work around it by restructuring my layouts so that `Navbar` is only ever loaded once at a higher level layout.
